import { StyleSheet } from 'react-native';
import { Colors, Fonts, Shadows } from '../../../../theme/ui';

export const styles = StyleSheet.create({
    container: { flex: 1, padding: 16 },
    title: { fontSize: 24, fontFamily: Fonts.bold, color: Colors.textPrimary },
    subtitle: { fontSize: 13, fontFamily: Fonts.medium, color: Colors.textSecondary, marginTop: 2, marginBottom: 14 },
    searchInput: {
        backgroundColor: Colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.border,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 12,
        fontFamily: Fonts.regular,
        color: Colors.textPrimary,
    },
    tripCard: {
        backgroundColor: Colors.surface,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: 14,
        marginBottom: 12,
        ...Shadows.card,
    },
    rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
    tripId: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.textPrimary, flex: 1 },
    badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
    badgeText: { color: '#fff', fontSize: 11, fontFamily: Fonts.semibold, textTransform: 'capitalize' },
    metaLine: { marginTop: 8, fontSize: 13, fontFamily: Fonts.medium, color: Colors.textSecondary },
    actionBtn: { marginTop: 12, backgroundColor: '#FFF8F0', borderColor: '#F7C98F', borderWidth: 1, borderRadius: 12, paddingVertical: 10, alignItems: 'center' },
    actionBtnText: { color: Colors.brandOrange, fontSize: 13, fontFamily: Fonts.bold },
    dangerBtn: { marginTop: 10, backgroundColor: '#FEF2F2', borderColor: '#FECACA', borderWidth: 1, borderRadius: 12, paddingVertical: 10, alignItems: 'center' },
    dangerBtnText: { color: Colors.danger, fontSize: 13, fontFamily: Fonts.bold },
    buttonRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
    halfButton: { flex: 1, marginTop: 0 },
    empty: { alignItems: 'center', paddingVertical: 50 },
    emptyText: { marginTop: 8, color: Colors.textSecondary, fontFamily: Fonts.medium, fontSize: 14 },
    detailScroll: { padding: 16, paddingBottom: 28 },
    detailCard: {
        backgroundColor: Colors.surface,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: 14,
        marginBottom: 12,
        ...Shadows.card,
    },
    detailSectionTitle: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.textPrimary, marginBottom: 8 },
    detailText: { fontSize: 13, lineHeight: 20, color: Colors.textSecondary, fontFamily: Fonts.medium, marginTop: 4 },
    mapWrap: { height: 240, borderRadius: 14, overflow: 'hidden', marginBottom: 12, ...Shadows.card },
});
