import { StyleSheet } from 'react-native';
import { Colors, Fonts, Shadows } from '../../../../theme/ui';

export const styles = StyleSheet.create({
    container: { flex: 1, padding: 16 },
    titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    title: { fontSize: 24, fontFamily: Fonts.bold, color: Colors.textPrimary },
    subtitle: { fontSize: 13, fontFamily: Fonts.medium, color: Colors.textSecondary, marginTop: 2, marginBottom: 14 },
    card: {
        backgroundColor: Colors.surface,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: 14,
        marginBottom: 12,
        ...Shadows.card,
    },
    cardTitle: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.textPrimary },
    badge: { backgroundColor: '#FEF3C7', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
    badgeText: { fontSize: 11, fontFamily: Fonts.bold, color: '#D97706' },
    line: { marginTop: 8, fontSize: 13, lineHeight: 19, fontFamily: Fonts.medium, color: Colors.textSecondary },
    reasonBox: { marginTop: 10, padding: 10, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12 },
    reasonLabel: { fontSize: 11, fontFamily: Fonts.semibold, color: Colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.4 },
    reasonText: { marginTop: 6, fontSize: 13, fontFamily: Fonts.medium, color: Colors.textPrimary, lineHeight: 19 },
    actionsRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
    btn: { flex: 1, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
    btnText: { fontSize: 13, fontFamily: Fonts.bold, color: '#fff' },
    btnReject: { backgroundColor: Colors.danger },
    btnApprove: { backgroundColor: Colors.success },
    empty: { alignItems: 'center', paddingVertical: 50 },
    emptyText: { marginTop: 10, fontSize: 14, fontFamily: Fonts.medium, color: Colors.textSecondary },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 18 },
    modalCard: { backgroundColor: Colors.surface, borderRadius: 16, padding: 16, ...Shadows.card },
    modalTitle: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.textPrimary, marginBottom: 10 },
    input: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        fontFamily: Fonts.medium,
        color: Colors.textPrimary,
        backgroundColor: '#F8F9FB',
        minHeight: 50,
        marginBottom: 12,
    },
    pickerItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
    pickerText: { fontFamily: Fonts.medium, color: Colors.textPrimary, fontSize: 14 },
    modalActions: { flexDirection: 'row', gap: 10, marginTop: 10 },
    modalCancel: { flex: 1, backgroundColor: '#F3F4F6', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
    modalCancelText: { fontFamily: Fonts.bold, color: Colors.textSecondary },
    modalConfirm: { flex: 1, backgroundColor: Colors.brandOrange, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
    modalConfirmText: { fontFamily: Fonts.bold, color: '#fff' },
});

