import { StyleSheet } from 'react-native';
import { Colors, Fonts, Shadows } from '../../../../theme/ui';

export const styles = StyleSheet.create({
    container: { flex: 1, padding: 16 },
    headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
    title: { fontSize: 24, fontFamily: Fonts.bold, color: Colors.textPrimary },
    subtitle: { fontSize: 13, fontFamily: Fonts.medium, color: Colors.textSecondary, marginTop: 2 },
    card: {
        backgroundColor: Colors.surface,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: Colors.border,
        padding: 14,
        marginBottom: 10,
        ...Shadows.card,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardHeaderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
    name: { fontSize: 16, fontFamily: Fonts.bold, color: Colors.textPrimary, flex: 1 },
    statusChip: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
    statusText: { fontSize: 11, fontFamily: Fonts.semibold, color: '#fff', textTransform: 'capitalize' },
    line: { fontSize: 13, fontFamily: Fonts.medium, color: Colors.textSecondary, marginTop: 6 },
    row: { flexDirection: 'row', gap: 8, marginTop: 12 },
    btn: { flex: 1, borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
    headerBtn: { flex: 0, paddingHorizontal: 14 },
    btnPrimary: { backgroundColor: Colors.brandOrange },
    btnDanger: { backgroundColor: '#FEE2E2' },
    btnTextPrimary: { color: '#fff', fontSize: 13, fontFamily: Fonts.bold },
    btnTextDanger: { color: Colors.danger, fontSize: 13, fontFamily: Fonts.bold },
    incidentActionButton: {
        backgroundColor: '#FFF8F0',
        borderWidth: 1,
        borderColor: '#F7C98F',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 7,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    incidentActionButtonText: {
        color: Colors.brandOrange,
        fontSize: 12,
        fontFamily: Fonts.bold,
    },
    searchInput: {
        backgroundColor: Colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.border,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 12,
        fontFamily: Fonts.regular,
        color: Colors.textPrimary,
    },
    filterRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
    filterChip: { borderWidth: 1, borderColor: Colors.border, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: Colors.surface },
    filterChipActive: { borderColor: Colors.brandOrange, backgroundColor: '#FFF8F0' },
    filterText: { fontSize: 12, fontFamily: Fonts.medium, color: Colors.textSecondary },
    filterTextActive: { color: Colors.brandOrange, fontFamily: Fonts.bold },
    empty: { alignItems: 'center', paddingVertical: 40 },
    emptyText: { marginTop: 8, fontSize: 14, color: Colors.textSecondary, fontFamily: Fonts.medium },
    formOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', padding: 16 },
    formCard: { backgroundColor: Colors.surface, borderRadius: 16, padding: 16, maxHeight: '80%' },
    formScrollContent: { flexGrow: 1, paddingBottom: 20 },
    formTitle: { fontSize: 18, fontFamily: Fonts.bold, color: Colors.textPrimary, marginBottom: 12 },
    formLabel: {
        fontSize: 12,
        fontFamily: Fonts.semibold,
        color: '#6B7280',
        marginBottom: 6,
        marginTop: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    formField: {
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 10,
        fontFamily: Fonts.regular,
        color: Colors.textPrimary,
    },
    inputIconWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        minHeight: 52,
        marginBottom: 10,
    },
    formFieldWithIcon: {
        flex: 1,
        marginLeft: 10,
        fontFamily: Fonts.regular,
        color: Colors.textPrimary,
        fontSize: 15,
        minHeight: 50,
    },
    formFieldReadOnly: {
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 10,
        fontFamily: Fonts.regular,
        color: Colors.textSecondary,
    },
    helperBox: {
        backgroundColor: '#FFF8F0',
        borderColor: '#F7C98F',
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 10,
    },
    helperText: {
        fontFamily: Fonts.medium,
        color: Colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
    },
    pickerFieldWrap: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: Colors.border,
        backgroundColor: '#F9FAFB',
        marginBottom: 10,
        overflow: 'hidden',
    },
    pickerField: {
        color: Colors.textPrimary,
    },
    formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
    formBtn: { borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10 },
    formCancel: { backgroundColor: '#F3F4F6' },
    formSubmit: { backgroundColor: Colors.brandOrange },
    formCancelText: { fontSize: 13, fontFamily: Fonts.bold, color: Colors.textSecondary },
    formSubmitText: { fontSize: 13, fontFamily: Fonts.bold, color: '#fff' },
    sectionTitle: { fontSize: 16, fontFamily: Fonts.semibold, color: Colors.textPrimary, marginBottom: 8 },
    selectField: {
        minHeight: 56,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        backgroundColor: '#F9FAFB',
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    selectFieldText: {
        fontSize: 18,
        lineHeight: 24,
        color: '#111827',
        fontFamily: Fonts.medium,
        flex: 1,
        marginRight: 10,
    },
    sheetOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        padding: 16,
    },
    sheetCard: {
        backgroundColor: Colors.surface,
        borderRadius: 18,
        padding: 14,
        maxHeight: '70%',
    },
    pickerCard: {
        backgroundColor: Colors.surface,
        borderRadius: 18,
        padding: 14,
    },
    sheetTitle: {
        fontSize: 16,
        fontFamily: Fonts.bold,
        color: Colors.textPrimary,
        marginBottom: 8,
    },
    sheetOptions: {
        maxHeight: 280,
    },
    sheetOption: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    sheetOptionText: {
        fontSize: 15,
        fontFamily: Fonts.medium,
        color: Colors.textPrimary,
    },
});
